# Site settings
title: No Escape
email: noescaperocks@gmail.com
facebook: https://www.facebook.com/noescaperocks
description: "Rock band in Lausanne"
baseurl: "/noescape"
url: "http://noescapeband.com"

# Build settings
markdown: kramdown
permalink: pretty
